version: '3.8'

services:
  claude-code-frontend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.frontend
    ports:
      - "5173:5173"    # Vite dev server
    volumes:
      - ..:/app:delegated
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_BACKEND_URL=http://localhost:3001
    depends_on:
      - claude-code-backend
    networks:
      - claude-network

  claude-code-backend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.backend
    ports:
      - "3001:3001"    # Backend API and WebSocket
    volumes:
      - ..:/app:delegated
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
    command: node server/index.js
    networks:
      - claude-network

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - claude-network

  # PostgreSQL for project metadata and chat history
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=claude_code_ide
      - POSTGRES_USER=claude
      - POSTGRES_PASSWORD=secure_password_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - claude-network

  # File watcher service for real-time updates
  file-watcher:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.watcher
    volumes:
      - ../src:/watch/src:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - WATCH_PATH=/watch/src
      - WEBSOCKET_URL=ws://claude-code-ide:3001
    depends_on:
      - claude-code-ide
    networks:
      - claude-network

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
  node_modules:
    driver: local

networks:
  claude-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16